before_install: cd terremotos

osx_image: xcode9.2
language: objective-c
xcode_project: terremotos.xcodeproj
xcode_scheme: terremotosTests
xcode_sdk: iphonesimulator8.3
podfile: terremotos/Podfile

script:
- xcodebuild ONLY_ACTIVE_ARCH="NO" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" clean build -project terremotos.xcodeproj
